pipeline {
  agent any
  tools { 
        maven 'Maven_3_8_6'  
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('CompileandRunSonarAnalysis') {
            steps {	
		sh 'mkdir -p sonar'    
		sh 'mvn clean verify -l sonar/log.txt sonar:sonar -Dsonar.projectKey=jenkins-sonar-ci_pipeline -Dsonar.organization=jenkins-sonar-ci -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6b97f056496f86ba20857ab4349e4ae20fd980a1'
		  }     
        }
        stage("Upload to Artifactory") {
                steps {
                 def uploadSpec = """{
                  "files": [
                   {
                    "pattern": "jenkins-pipeline-examples/resources/.*A[A-z]tifactory.*.zip",
                   "target": "libs-snapshot-local/",
                      "regexp": "true"
                 },
                 {
                     "pattern": "jenkins-pipeline-examples/resources/.*(A|a)rtifactory.*.zip",
                    "target": "libs-snapshot-local/",
                    "regexp": "true"
                 }
         ]
                }"""
            }
        }      
    }
}
