pipeline {
  agent any
  tools { 
        maven 'Maven_3_8_6'  
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('CompileandRunSonarAnalysis') {
            steps {	
		sh 'mkdir -p sonar'    
		sh 'mvn clean verify -l sonar/log.txt sonar:sonar -Dsonar.projectKey=jenkins-sonar-ci_pipeline -Dsonar.organization=jenkins-sonar-ci -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6b97f056496f86ba20857ab4349e4ae20fd980a1'
		  }     
        }
        stage('Publish to Artifactory') {
            steps {
                script {
                    // Configure Artifactory details
                    def server = Artifactory.server('artifactory')

                    // Define the Artifactory upload specification 
                    def uploadSpec = """
                        {
                            "files": [
                                {
                                    "pattern": "target/*.jar",
                                    "target": "default-libs-release"                              }
                            ]
                        }
                    """

                    // Upload Artifact to Artifactory
                    server.upload(uploadSpec)
                }
            }
        }
        stage('Xray Scan') {
            steps {
                script {
                    def scanConfig = [
                        file: 'Jenkinsfile',
                        watchBuild: true,
                        failBuild: true,
                        includeEnvVars: true
                    ]
                    
                    xrayScan scanConfig
                }
            }
        }                   
    }
}
